# Generated by Django 5.2.6 on 2025-12-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0004_announcment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcment",
            name="attatchment",
            field=models.FileField(blank=True, null=True, upload_to="announcements/"),
        ),
    ]
