# Generated by Django 5.2.7 on 2025-12-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_alter_announcment_attatchment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MrMissNit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028')], max_length=4)),
                ('mr_name', models.CharField(max_length=100)),
                ('mr_photo', models.ImageField(upload_to='mr_miss_nit/')),
                ('mr_department', models.CharField(max_length=100)),
                ('mr_description', models.TextField(blank=True)),
                ('miss_name', models.CharField(max_length=100)),
                ('miss_photo', models.ImageField(upload_to='mr_miss_nit/')),
                ('miss_department', models.CharField(max_length=100)),
                ('miss_description', models.TextField(blank=True)),
                ('event_description', models.TextField()),
                ('judging_criteria', models.TextField(help_text='Enter each criterion on a new line')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
