# Generated by Django 5.2.7 on 2025-12-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['category', 'event_name']},
        ),
        migrations.AlterModelOptions(
            name='studentregistration',
            options={'ordering': ['-registered_at']},
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='college',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, choices=[('LITERARY', 'LITERARY EVENTS'), ('ATHLETICS', 'ATHLETICS EVENTS'), ('CULTURAL', 'CULTURAL EVENTS'), ('GAMES', 'GAMES'), ('SPORTS', 'SPORTS')], default='LITERARY', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='branch',
            field=models.CharField(blank=True, choices=[('CSE', 'Computer Science & Engineering'), ('ECE', 'Electronics & Communication Engineering'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('MBA', 'Master of Business Administration'), ('MCA', 'Master of Computer Applications'), ('BBA', 'Bachelor of Business Administration'), ('BCA', 'Bachelor of Computer Applications')], default='CSE', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='regd_no',
            field=models.CharField(default='LITERARY', max_length=20, verbose_name='Registration Number'),
            preserve_default=False,
        ),
    ]
