# Generated by Django 5.2.6 on 2025-12-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0002_alter_event_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentregistration",
            name="branch",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CSE", "CSE"),
                    ("EE", "EE"),
                    ("ME", "ME"),
                    ("CIVIL", "Civil"),
                    ("MBA", "MBA"),
                    ("MCA", "MCA"),
                    ("BBA", "BBA"),
                    ("BCA", "BCA"),
                ],
                default="CSE",
                max_length=50,
                null=True,
            ),
        ),
    ]
