# Generated by Django 5.2.7 on 2025-12-17 17:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_studentregistration_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the event', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.CharField(blank=True, help_text="e.g., '3-5 minutes', '60 minutes', 'Multiple Rounds'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this event currently open for registration?'),
        ),
        migrations.AddField(
            model_name='event',
            name='judging_criteria',
            field=models.TextField(blank=True, help_text='Judging criteria for the event', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.IntegerField(default=1, help_text='Maximum number of participants (1 for solo, more for teams)'),
        ),
        migrations.AddField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes for admin (not visible to public)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, help_text='Last date for registration', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='rules',
            field=models.TextField(blank=True, help_text='Rules and guidelines for participants', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='team_size',
            field=models.CharField(blank=True, help_text="e.g., 'Solo', 'Team of 4', 'Duo', etc.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
