# Generated by Django 5.2.7 on 2025-12-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_event_created_at_event_description_event_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Dynamic Categories',
                'ordering': ['name'],
            },
        ),
    ]
